### ISSUE TITLE
Support of graphic-margin vendor option in FillSymbolizer

### ISSUE THREAD

**Issue by fgravin** [Bayer-Group/geostyler-geoserver-sld-parser#8]
Hi,

I want to be able to set the `graphic-margin` of a background pattern in a polygon symbolizer.
See https://docs.geoserver.org/latest/en/user/styling/sld/extensions/margins.html for more information.

So I think of creating a new interface
```ts
interface GeoserverFillSymbolizer extends FillSymbolizer {
  graphicMargin?: number[];
}
```

Then overriding the methods `getFillSymbolizerFromSldSymbolizer` and `getSldPolygonSymbolizerFromFillSymbolizer` as it's done for `TextSymbolizer` in this repository.

What do you think ?
Thanks

**Comment by akuma1** [comment]
I have merged related PR after resolving some merge conflicts. Closing this issue now.
